# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Build and test
      - name: Build
        run: mvn clean package
      # Create Sonargraph XML report
      - name: Sonargraph Report
        run: mvn compile com.hello2morrow:sonargraph-maven-plugin:12.2.0:dynamic-report -Dmaven.repo.remote=https://mvnrepository.com/repos/hello2morrow -Dsonargraph.autoUpdate=true -Dsonargraph.activationCode=1E05-733B-3BCD-E9A7 -Dsonargraph.reportFormat=xml -Dsonargraph.reportName=${{ env.GITHUB_REF_NAME }}
      - name: Download metric extractor
        run: wget https://github.com/sonargraph/metric-extractor/releases/download/1.0/MetricExtractor-1.0.jar
      - name: Extract metrics from  XML report
        run: java -jar MetricExtractor-1.0.jar target/sonargraph/${{ env.GITHUB_REF_NAME }}.xml

